### ISSUE TITLE
Dotfiles

### ISSUE THREAD

**Issue by benswinburne** [newmarcel/KeepingYouAwake#114]
Is it possible to configure KeepingYouAwake using a configuration file?

In an ideal world it'd look for .keepingyouawake or equivalent in the home directory of the user if it doesn't already?

**Comment by newmarcel** [comment]
This is currently not in scope of this project because I'm limiting the file system access of KYA to its own sandbox container in v1.5.0. Which means, preferences are only read from the `info.marcel-dierkes.KeepingYouAwake.plist` file.

- Dotfiles are more common for command line tools.
- You could of course build your own wrapper around the `caffeinate` utility that uses dotfiles instead.
- You could also write a shell scripts that uses the `defaults` command to apply preferences to KeepingYouAwake
