### ISSUE TITLE
"Default Activation Duration" should have more options / free input

### ISSUE THREAD

**Issue by jakobjw** [newmarcel/KeepingYouAwake#125]
It would be great if the "Default Activation Duration" had more options, like:
- 8 hours
- 10  hours

Or, even better, the possibility to enter a desired number of hours manually.

**Comment by newmarcel** [comment]
Absolutely! It really makes sense to have a fully customizable list for the durations. This could be integrated into the `Preferences` window.

Thanks for the suggestion 👍 I will consider this for the next feature release.

**Comment by DavidChenware** [comment]
> It would be great if the "Default Activation Duration" had more options, like:
> 
> * 8 hours
> * 10  hours
> 
> Or, even better, the possibility to enter a desired number of hours manually.

As a real use case, those hours would be perfect because it matches up roughly with a regular work day.

1. Get in to the office
1. Wake up computer
1. Click cup icon
1. Do work all day
1. Don't have to re-wake computer and have all the windows and monitors get jumbled up
1. Go home at end of day
1. Have computer go to sleep

**Comment by newmarcel** [comment]
I can now confirm that a fully customizable menu of activation durations will be part of the next release. Thanks again for the suggestion and your patience 😸
