### ISSUE TITLE
Feature Request: Simple download page or publish in Mac App Store

### ISSUE THREAD

**Issue by edmundito** [newmarcel/KeepingYouAwake#129]
Hello, I wanted to suggest to make this available either as a dmg download from a website or via the Mac App store. The reasoning behind this is that I as a more technical person have no problem going to GitHub and figuring out what to do. But to share this with people who are less technical is a bit more difficult. This is by far one of the essential tools for mac, especially in the workplace.

I think providing simple one page website with some info about what this does and a download would go a long way, even something that published with GitHub pages. Another option is to add it to the Mac App Store but I understand there are extra steps and costs to get there.

**Comment by newmarcel** [comment]
Thank you very much for this feedback 😀

When I started the project years ago I actually saw the missing website as a feature because this _(kind of)_ removed the expectation some users might have that I provide professional support… because in the end this is just a fun little side project of mine that I occasionally invest some time in. This same pressure would apply to the App Store.

---

But recently I really started thinking about the App Store _(because tooling and updating got worse for non-App Store apps: Notarization, Sparkle trouble…)_:

- the cost factor is not an issue here because I'm paying for the Apple Developer Program already
- with an App Store presence I wouldn't need a giant website, just a tiny bit of info, a nice little App Store badge and a privacy policy
- all of this might fail and Apple might reject the app

So there are some thoughts I'm dealing with right now:

* how would my users feel about moving to the App Store?
* similar paid apps are in the App Store, I don't want to eat their lunch
* I don't want to maintain an App Store version + download version… just one of those

Thanks for triggering this thought process in me 😁

**Comment by alexandreleroux** [comment]
Thanks @newmarcel , my personal opinion:
* +1 for moving to the App Store, as long as the app remains free (or at worse, very very cheap?). Any payment is a barrier to adoption, which would be sad because I want more people to benefit from the nice and useful open source KYA
* I would not worry about another App's lunch, I see this as sane and expected competition :-)

Hope this feeds your thought process ;-)

**Comment by ahydronous** [comment]
@newmarcel 

If you have to pick one of those, please keep it on here instead of the Mac App store. I (and most other tech people I know) barely if ever use it, and those are the primary users of something like KeepingYouAwake. There is also already a full featured alternative in the Mac App store (Amphetamine).

**Comment by newmarcel** [comment]
Well, I finally went ahead and created an official website https://keepingyouawake.app/ _(work in progress)_.
This will always link to the latest release, nothing fancy.
It also teasers the new app icon and main screenshot that I plan to roll out with macOS Big Sur 😀.

Thanks again for all the feedback. I will stay off the App Store for now, as there is no immediate reason to do so.

**Comment by DanielWeeber** [comment]
Is this a universal binary supporting m1 macs? It does not state that on the website or here on github

**Comment by newmarcel** [comment]
@DanielWeeber Version 1.6.0 supports both Intel Macs and Apple Silicon Macs. _(This is noted as "arm64 support" in the release notes, because it was released before the M1 Macs were unveiled)_.

**Comment by DanielWeeber** [comment]
Nice, thank you. Maybe show that on the website as "universal" binary or sth to make this info easier to find?
