### ISSUE TITLE
Support for macOS Catalina

### ISSUE THREAD

**Issue by AlexandrDemin** [newmarcel/KeepingYouAwake#135]
Hello. Thank you for developing so useful app for free. Do you plan to add Catalina support? I'm on beta right now and my macbook goes to sleep after closing the lid even if the app is running.

**Comment by newmarcel** [comment]
Hi! The current version is mostly compatible with macOS Catalina, as far as I can see. The only "issue" I can find is that the system will ask for notification access even if you don't need it. I'm working on this.

Your described behavior is not part of this app at all, KYA cannot keep your Mac awake if you close the lid. This would cause heat and battery waste issues, so it is not and won't be part of the app.

If you notice any other Catalina-specific issues, please feel free to open a new ticket.

Thanks 👍

**Comment by AlexandrDemin** [comment]
Ok, I see. Thanks

**Comment by varenc** [comment]
@AlexandrDemin just run `sudo pmset disablesleep 1` to preventing your mac from sleeping, even when the lid is closed and you're running on battery.  Be very careful with this though since if you don't disable it your laptop will always drain itself down when it's unplugged.  I have a crontab which re-enables sleep if I forget to do it myself.
