### ISSUE TITLE
Russian translation of KeepingYouAwake

### ISSUE THREAD

**Issue by Kromsator** [newmarcel/KeepingYouAwake#143]
Hello Marcel Dierkes.
I have translated your KeepingYouAwake program into Russian. The translation is complete. The program itself are attached to this letter.

___With respect Alexey Zhdanov___

(https://github.com/newmarcel/KeepingYouAwake/files/4015034/KeepingYouAwake.app.zip)

<img width="415" alt="screenshot_613" src="https://user-images.githubusercontent.com/59431528/71657788-4d0b4400-2d7c-11ea-903b-54063ffef699.png">
<img width="448" alt="screenshot_614" src="https://user-images.githubusercontent.com/59431528/71657796-572d4280-2d7c-11ea-98fd-c17dba43ea1a.png">
<img width="450" alt="screenshot_615" src="https://user-images.githubusercontent.com/59431528/71657801-62806e00-2d7c-11ea-9362-c885da1541dc.png">
<img width="450" alt="screenshot_616" src="https://user-images.githubusercontent.com/59431528/71657816-6d3b0300-2d7c-11ea-9666-4ac827bfaa38.png">
<img width="450" alt="screenshot_619" src="https://user-images.githubusercontent.com/59431528/71658010-37e2e500-2d7d-11ea-9273-2be0255a1241.png">
<img width="515" alt="Снимок экрана 2020-01-03 в 10 00 54" src="https://user-images.githubusercontent.com/59431528/71703526-fbac9480-2e0f-11ea-802c-8092e5158908.png">

**Comment by newmarcel** [comment]
Hi! Thanks for the effort 👍 !

The workflow I recommend for translations usually is creating a [pull request](https://github.com/newmarcel/KeepingYouAwake/pulls) where you provide a new XLIFF file _(see Localizations/KeepingYouAwake)_… or even the updated `strings` files.

See [this guide](https://github.com/newmarcel/KeepingYouAwake/blob/master/Localizations/README.md) for additional notes.

The reason why I'm writing this is that I cannot use the ZIP archive you provided because it contains a compiled app but not the actual translation files. There is no way for me to integrate this back into the source code.

If this doesn't discourage you I would gladly add your Russian translation to the app 😃.

**Comment by Kromsator** [comment]
Wrote where it is necessary. Delete this branch.
