### ISSUE TITLE
Cyclance Protect is blocking updates

### ISSUE THREAD

**Issue by 1oglop1** [newmarcel/KeepingYouAwake#160]
Hi, 
Our company uses CyclancePROTECT and it prevents the app from updating (thank god not from running! it's great).

I'm not sure if there is anything you can do, but I guess it's likely due to the nature of the program being a security issue by preventing sleeping.

Here is the only log I can get, I hope it will be somewhat helpful.

Feel free to close the issue if you cannot resolve it.

```
"When","Category","Event","Details"
12/7/2020 9:21:14 AM,Threat,Changed (Quarantined ),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc/Contents/MacOS/org.sparkle-project.InstallerConnection
12/7/2020 9:21:14 AM,Threat,Changed (Quarantined ),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/org.sparkle-project.InstallerLauncher
12/7/2020 9:21:14 AM,Threat,Changed (Quarantined ),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc/Contents/MacOS/org.sparkle-project.InstallerStatus
12/7/2020 9:21:14 AM,Threat,Changed (Quarantined ),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/Autoupdate
12/7/2020 9:21:14 AM,Threat,Changed (Quarantined ),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/Updater.app/Contents/MacOS/Updater
12/7/2020 9:18:46 AM,Threat,Changed (Detected),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc/Contents/MacOS/org.sparkle-project.InstallerConnection
12/7/2020 9:18:46 AM,Threat,Changed (Detected),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/org.sparkle-project.InstallerLauncher
12/7/2020 9:18:46 AM,Threat,Changed (Detected),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc/Contents/MacOS/org.sparkle-project.InstallerStatus
12/7/2020 9:18:46 AM,Threat,Changed (Detected),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/Autoupdate
12/7/2020 9:18:46 AM,Threat,Changed (Detected),/Applications/KeepingYouAwake.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/Updater.app/Contents/MacOS/Updater
```

**Comment by newmarcel** [comment]
Hi! I would say that your security program is configured a bit too strict 😀. The files you have listed are part of the update system ("Sparkle"). If these are blocked, the app will never update properly, as you have described. Alternatively you can simply download new releases manually, there are not too many throughout the year ^^.

Since "Sparkle" is used by other apps as well these might have problems too. If you have access to some kind of block list, you can probably also add exceptions.

> but I guess it's likely due to the nature of the program being a security issue by preventing sleeping.

The used methods to keep the system awake are actually officially documented Apple APIs and no unofficial hacks or similar methods are used that could endanger system integrity.

Since I have no control over any security software used out there in the world, I will close this issue. If you notice similar problems with other apps, maybe you can get in touch with your security software support instead?
