### ISSUE TITLE
doesn't seem to work on Big Sur

### ISSUE THREAD

**Issue by mangoducksparkles** [newmarcel/KeepingYouAwake#167]
This app was working for me perfectly, but then I updated my macbooks to Big Sur. Now my macbooks seem to go to sleep when I close their lids. Tasks are interrupted by closing the lid, consistent with the system sleeping. The system logs a sleep event on lid close, but it's followed quickly by a wakeup signal, and I'm unsure if this is expected behavior. This is happening on two different macbooks, both running 1.6.0 version.

**Comment by chaganiu** [comment]
+1

**Comment by newmarcel** [comment]
Hi, you might want to look into an alternative tool for you use case. `KeepingYouAwake` will not keep your Mac awake when you close the lid of your MacBook. That's not something I plan to support in the long term because of thermal constraints of the different machines out there and the limitations of the underlying system APIs I use to keep the Mac awake.

I probably need to update the README to clarify this. I'm sorry that this wasn't made clear enough until now and broke for you.

**Comment by fharper** [comment]
Good idea to update the README. I spent too much time trying to figured out why it wasn't working for me.
