### ISSUE TITLE
Prevent sleep on lid close

### ISSUE THREAD

**Issue by cdwilson** [newmarcel/KeepingYouAwake#19]
Would it be possible to add a setting in KYA to prevent sleep on lid close when plugged into AC power?

**Comment by newmarcel** [comment]
Hi, if I understand you correctly you want to revert to the sleep behaviour from version 1.2.0 and below. I changed the sleep modes with the 1.2.1 update. There is still a way to revert the change, just have a look at the release notes for v1.2.1: https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.2.1

So you basically have to paste the line `defaults write info.marcel-dierkes.KeepingYouAwake.PreventSleepOnACPower -bool YES` into your terminal to make it work.

I hope this fixes the issue for you.

Greetings,
Marcel

**Comment by samholmes** [comment]
What about preventing sleep on lid close when **not** plugged into AC power?

**Comment by cdwilson** [comment]
@newmarcel yes, I've got an old Macbook Pro I'd like to use as a server with the lid closed and AC power connected continuously.  I'd like to use KYA to prevent the laptop from sleeping when I close the lid.  Would be nice to have a right click menu option for toggling this (instead of remembering the command).

**Comment by newmarcel** [comment]
@samholmes I probably won't support this mode of sleep prevention because it can potentially damage your Mac if it runs hot… This is also the reason why I hid the sleep prevention when on AC power with the last update as a power user feature. Also since I'm just wrapping Apple's `caffeinate` command, I can only support the sleep modes that this command line tool supports. *(run `man caffeinate` in the Terminal to see available options)*

@cdwilson The `defaults write …` command is only required once. After you run it in the terminal the power mode stays active and you can use, quit, reopen KYA normally and as many times as you want.

**Comment by samholmes** [comment]
@newmarcel How about a timer set on the purported mode? The timer would allow just enough time to be able to close your lid and more around an office space without losing network connection, but not enough time to cause some serious damage.

**Comment by BrendanAnnable** [comment]
To extend on the suggestion by @samholmes, could the "prevent sleep on lid close" setting be integrated with the "deactivate when the battery is low" setting? This should be the best of all worlds, allowing:

1. Walking around an office with the lid closed and not losing your network connection.
2. No risk of damage, since it will turn off and sleep if the battery runs out.

It seems all the functionality is already here, so it just needs exposing as a setting. I'd be surprised if the majority of users of this program weren't in this use case, and I don't see a downside to it?

**Comment by zyazzy** [comment]
So whats the conclusion? Closing lid would sleep the mac right?

**Comment by lordgiotto** [comment]
Sorry if I reopen the question, but one year passed since your answer and maybe something changed (for exemple the commit b0d851f7e26b063fc3e73c3432b38abd480d01cf of the last December removed the `info.marcel-dierkes.KeepingYouAwake.PreventSleepOnACPower` option).

*Your app is capable, in any way, to prevent sleep on lid closing? 
Or it's not designed for that / you prefer to not implement it / it's too dangerous to use?*

I would use that feature a lot while I stream a movie to my chromecast :P 

Thank you very much! :)

**Comment by mk2soldier** [comment]
Guys, you could always use InsomniaX, it has exactly that feature (prevent sleep on closed lid).

**Comment by sreenadhp** [comment]
Just to clarify:

1. should I replace KYA with InsomniaX, as IX includes all the features of KYA and is capable of not sleeping when the lid closes
2. Or can KYA & IX run parallel as both does different things and can co-exist without conflicts.

**Comment by newmarcel** [comment]
Sorry for the delayed answer 😓. As it stands right now, I probably won't support this feature anytime soon.

If [InsomniaX](https://github.com/semaja2/InsomniaX) is working for you, then please go ahead. It's a great tool :thumbsup:

Running both apps together is most definitely not a good idea as they might interfere with each other.
