### ISSUE TITLE
Automatic update from 1.3.0 to 1.3.1 works as expected

### ISSUE THREAD

**Issue by daenney** [newmarcel/KeepingYouAwake#42]
<img width="732" alt="screenshot 2016-01-04 11 09 03" src="https://cloud.githubusercontent.com/assets/569574/12087490/bbdba816-b2d3-11e5-89b5-77fcd41c1384.png">

Not entirely sure what's going on but at least the statement that Github has disabled HTTPS for Pages doesn't appear to be true and the update has reached me just fine. Just about every other resource I have hosted on Github Pages works fine over HTTPS too and I can't find any announcement by Github on the matter either which I would expect to have seen upfront.

**Comment by alexandreleroux** [comment]
@daenney are you on MacOS X 10.11? On my computers, KYA update worked on my macs using <10.11, but failed with 10.11, just like the KYA devs indicated (in the message you copied in this ticket). Happy 2016 :-) -- Alex

**Comment by daenney** [comment]
I'm on 10.11.2

<img width="698" alt="screenshot 2016-01-04 14 22 59" src="https://cloud.githubusercontent.com/assets/569574/12090389/d2095546-b2ee-11e5-908b-55920b074e43.png">

**Comment by newmarcel** [comment]
I'm glad that the upgrade process worked for you. The update check should have failed on 10.11, because I failed to properly configure App Transport Security. I just hope that it will never break again so I can concentrate on preparing the next version of the app 😃

Thanks for the feedback, I'm closing this issue now.
