### ISSUE TITLE
Capability to include Beta versions in 'Check for Updates'

### ISSUE THREAD

**Issue by alexandreleroux** [newmarcel/KeepingYouAwake#44]
Feature suggestion: the capability to include beta versions in the 'Check for Updates...' process. Disabled by default.

This would make the process of upgrading to beta versions so easy that more of us would test those beta versions :-) Thoughts / comments? Cheers -- Alex

**Comment by newmarcel** [comment]
Sounds reasonable :+1: 

I could implement it like TextMate does, with a popup menu to select `stable releases` or `beta releases`.

<img width="389" alt="bildschirmfoto 2016-02-06 um 20 01 10" src="https://cloud.githubusercontent.com/assets/406920/12868721/94029dce-cd0c-11e5-95a3-bb2ea0830b8c.png">

I need to streamline my release process first, because creating the `appcast.xml` file for Sparkle is quite a hassle at the moment. But I guess it's worth the effort to have more people test the betas! I'll just automate the whole process.

Thanks for the suggestion :grinning:

**Comment by newmarcel** [comment]
OK. This is now implemented and will ship beginning with 1.4.0beta2.

![pre-release updates-fs8](https://cloud.githubusercontent.com/assets/406920/13723633/8d7599be-e86b-11e5-95d4-56bdbc462f79.png)

**Comment by alexandreleroux** [comment]
Great! Thanks newmarcel, I think that's going to be a useful new capability :-) -- Alex

**Comment by alexandreleroux** [comment]
Closing this ticket since version 1.4.0 has been released and this feature is included. Thanks @newmarcel ! -- Alex
