### ISSUE TITLE
brew cash can't download

### ISSUE THREAD

**Issue by dukegod** [newmarcel/KeepingYouAwake#46]
in china, i can't download;

error iinfo:
`curl: (52) Empty reply from server`

can you support brew for installing

**Comment by newmarcel** [comment]
Thanks for raising this issue! But I'm afraid there is not much I can do about it, since I don't host the binary distributions of the app myself.

Can you at least checkout and build the source code? I guess the direct download via [GitHub releases](https://github.com/newmarcel/KeepingYouAwake/releases) will also fail because it is used for `brew cask`…
