### ISSUE TITLE
Preference label rendered incorrectly

### ISSUE THREAD

**Issue by redbassett** [newmarcel/KeepingYouAwake#65]
The default activation duration preference is displaying its label text below the options and description text:
![screen shot 2016-10-26 at 15 13 05](https://cloud.githubusercontent.com/assets/1379565/19741615/61fab4fe-9b8f-11e6-86ce-73ce1a0c7a32.png)

**Comment by alexandreleroux** [comment]
@redbassett that's in which version? This looks fine to me in 1.4.0 (140). Thx

**Comment by redbassett** [comment]
Sorry! Missed that part. `1.4.0 (140)` installed via brew. Persists after re-install (`brew cask uninstall`). Running on OS `10.10.5`.

**Comment by newmarcel** [comment]
I booted up my OS X VMs to verify and you're right, this looks broken, but it's only happening on Yosemite. El Cap and newer are fine.

![screenshot](https://cloud.githubusercontent.com/assets/406920/21570941/d9551044-ceca-11e6-83d4-9b951b90cd8d.png)

I'll have a look, but this bug won't make it to the top of my prio list, because Yosemite is already a couple of years old 😉

**Comment by redbassett** [comment]
No problem. I'm stuck on Yosemite for some interesting reasons, but as long as it's not in newer versions, all is well.

**Comment by Eitot** [comment]
I am guessing that this may be caused by the `preferredMaxLayoutWidth` property of the NSTextField. In Interface Builder, there are three options: ‘automatic’, ‘first runtime layout width’ and ‘explicit’. The first two seem to be unique to IB, because `preferredMaxLayoutWidth` only expects a float.

The first option (‘automatic’) is not available in Yosemite, but this is the one the project currently uses. For some reason, this is not reported as a warning, even though I have seen it many times before. I think that the fall-back value for Yosemite would be ‘first runtime layout width’, which causes the text field not to grow wider than the value it has in Interface Builder. At runtime, the text field will accordingly not behave as expected. I am suspecting that this will also be the case for translations, particularly those that result in a wider label than in English.

The solution would be to use an explicit value. You can use something large, such as 400px. The text field should still shrink to its smallest intrinsic width, but it will have ample space to widen if it needs the space.

![screen shot 2017-03-06 at 16 40 13](https://cloud.githubusercontent.com/assets/15073177/23616919/98aa852a-028b-11e7-9430-2abb4b8fd5b1.png)

**Comment by newmarcel** [comment]
I don't think I will fix this anytime soon. I plan to keep support for macOS Yosemite but treat this layout issue as a known issue. I hope many users have moved on to more recent versions of macOS.
